### ISSUE TITLE
Any capacity for using multiple databases?

### ISSUE THREAD

**Issue by MitchellW-DWL** [Particular/install-sql-server-action#11]
Connection string generated has `Initial Catalog=nservicebus` by default I believe, and this can be changed using the provided `with` statements, but is there anyway to generate a connection string with the `Initial Catalog` parameter omitted from the connection string? Or generate multiple with different values?

**Comment by danielmarbach** [comment]
@MitchellW-DWL 

These setup actions are currently geared towards fulfilling the needs we have for our builds and are not focused to be "general" purpose. It might very well be that they don't fit the needs of someone else. It is also quite likely that we are not prioritizing any feature requests that are outside our usage.

Would it be an option for you to take the written environment variable? Parse it. Create new connection strings to your liking and then propagate them to other env variables that you see fit for your needs? 

We do something similar here

https://github.com/Particular/NServiceBus.Persistence.Sql/blob/master/.github/workflows/ci.yml#L156-L162

**Comment by MitchellW-DWL** [comment]
Yeah that'll suffice my needs - was holding out hope there might have been a way using the package.

Thanks for the reference material :)

**Comment by danielmarbach** [comment]
Please don't get me wrong, you can use this undoubtedly and any changes we will make will be versioned accordingly.
