### ISSUE TITLE
considering AdventureWorks2012 as an extra sample database

### ISSUE THREAD

**Issue by smoothdeveloper** [Particular/install-sql-server-action#14]
I'm trying to setup github actions that rely on mssql in context of CI for https://github.com/fsprojects/FSharp.Data.SqlClient/

this project uses AdventureWorks2012 (but could be more recent I guess):

https://github.com/fsprojects/FSharp.Data.SqlClient/blob/master/tests/SqlClient.Tests/AdventureWorks2012_Data.zip

I wonder if you'd make it convenient for people picking up "how do I MSSQL in github actions" even farther than the nservicebus database, by adding a version of adventureworks to the documentation here, and to simplify things for all repositories that use this database (I'd guess, it could be more than nservicebus).

Thanks for the github actions reference in anycase!

**Comment by lailabougria** [comment]
Hi @smoothdeveloper,

These setup actions are currently geared towards fulfilling our individual needs regarding build and deployment, and weren't intended for general usage. Therefore, it is unlikely that we'll prioritise any feature requests that are outside our usage, but we still chose to make them open-source as we believe the actions could serve as good basis to draw inspiration from.

**Comment by smoothdeveloper** [comment]
@lailabougria understood! Thanks for having them in the open, I'll close the issue.
