### ISSUE TITLE
How to specify a SQL server version?

### ISSUE THREAD

**Issue by KarloX2** [Particular/install-sql-server-action#16]
Hello!

I'm using `Particular/install-sql-server-action@v1.0.0` in a github action (running in windows-latest) and it works nicly. I'm just wondering if it will start downloading some future version of SQL Server instead of currently version 2022, once a later RTM becomes available? I'd like to specify version 2022 explicitly, if possible?

**Comment by danielmarbach** [comment]
Hi @KarloX2 

At the moment, we would basically forward the version once we need the newer version of SQL Server and release a new minor or major of the setup action.

Technically speaking, we could add a version parameter to the github action YAML that allows specifying a version. The biggest problem is that the Chocolatey versions for windows follow a different version schema from the docker version tags on Linux. Unfortunately, Chocolatey [doesn't support a proper version ranges](https://github.com/chocolatey/choco/issues/800) when selecting a package, which complicates things a lot. 

Spitballing a solution approach, I think we could do a [Chocolatey find](https://docs.chocolatey.org/en-us/choco/commands/find/) or list of the specific package and then add some custom PowerShell script that finds the nearest matching version and installs that. 

Maybe something like

```powershell
param (
    [string]$VersionPrefix = "2022"  # Default version prefix if none provided
)

# Searching for available versions
$availableVersions = choco search sql-server-express --all-versions | Where-Object { $_ -like "*$VersionPrefix*" }

# Extracting and sorting the versions
$sortedVersions = $availableVersions |
                  Select-String -Pattern 'sql-server-express\s+(\d+\.\d+\.\d+\.\d+)' -AllMatches |
                  ForEach-Object { $_.Matches.Groups[1].Value } |
                  Sort-Object -Version -Descending

# Selecting the newest version
$newestVersion = $sortedVersions[0]

# Installing the newest version if found
if ($newestVersion) {
    Write-Host "Installing SQL Server Express version $newestVersion..."
    choco install sql-server-express --version $newestVersion -y
} else {
    Write-Host "No versions found matching the prefix '$VersionPrefix'."
}
```

would do the trick

The setup-repositories we have are provided as is and are built mostly for our internal needs. You'd be free to fork those and then reference it in your build actions from your forked repositories. That being said, if you would contribute an approach that makes it work on Linux and Windows allowing us to specify a version like "2022" I'd be happy to review it and potentially even bring it in.

**Comment by danielmarbach** [comment]
I did a quick spike PR https://github.com/Particular/install-sql-server-action/pull/17

What worries me the most is that over time chocolatey actually changed their versioning schema. This might break again with the next release

**Comment by KarloX2** [comment]
@danielmarbach Thank you for your quick response. I will test it as soon as it is available. I think this is a really useful extension.

**Comment by danielmarbach** [comment]
@KarloX2 v1.2.0 contains the parameter.

**Comment by KarloX2** [comment]
Very good. So shall I specify `uses: Particular/install-sql-server-action@v1.2.0` in order to make use of the `sqlserver-version: 2022` setting? I'm confused because the readme.md has such a sample but uses ...@v1.0.0

**Comment by danielmarbach** [comment]
We are not updating the version in the readme everytime we release. These are just examples. As you noticed, we are also not doing any types of release notes in these actions because we consider them mostly for our own purposes.

**Comment by KarloX2** [comment]
A ok, I see.

But would the sample you provide in README.MD (with ..v1.0.0) work at all, without changing to ..v1.2.0) ?

```
steps:
  - name: Install SQL Server
    uses: Particular/install-sql-server-action@v1.0.0
    with:
      connection-string-env-var: SQL_SERVER_CONNECTION_STRING
      sqlserver-version: 2019
      catalog: nservicebus
```

_With_ the change to ..v1.2.0 it seems to work nicely. I didn't try without that change.

**Comment by danielmarbach** [comment]
Ah, now I understand. Yeah that is misleading. Sorry for that. See https://github.com/Particular/install-sql-server-action/pull/18

**Comment by KarloX2** [comment]
Great, thanks for the good work!
________________________________
Von: Daniel Marbach ***@***.***>
Gesendet: Friday, June 28, 2024 12:39:16 PM
An: Particular/install-sql-server-action ***@***.***>
Cc: Karsten Strobel ***@***.***>; Mention ***@***.***>
Betreff: Re: [Particular/install-sql-server-action] How to specify a SQL server version? (Issue #16)


Ah, now I understand. Yeah that is misleading. Sorry for that. See #18<https://github.com/Particular/install-sql-server-action/pull/18>
